# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action w# Comment that will be sent if an issue is judged to be closed
comment: "由于issue并未按照模板填写,即将被bot自动关闭。"
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "关于你要提交的问题"
  - "是否搜索了issue"
  - "是否仔细阅读了教程"
  - "你使用的哪种运行方案"
  - "详细叙述"
  - "具体问题"
  - "详细日志"
- content:
# Example 2: feature request
  - "Motivation / Use Case"
  - "Expected Behavior"
  - "Other Information"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
exception:
  - "Zero-S1"ill run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
